name: Windows-RDP-Auto-Shutdown
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github

      - name: Setup User and RDP
        run: |
          $Password = ConvertTo-SecureString "Fikru417@4" -AsPlainText -Force
          New-LocalUser "RDPUser" -Password $Password -Description "Access"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
          Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Wait for 6 Hours
        run: |
          Write-Host "Connect now. Machine will auto-destruct in 6 hours."
          # Instead of a loop, we just tell the system to wait for 21600 seconds
          Start-Sleep -Seconds 21600
